export {
  type ComposeComment,
  type ComposeDocument,
  type ComposeEditorView,
  type ComposePresentation,
  emptyComposeDocument,
  isBlankComposeData,
  isComposeDocument,
  isComposeEditorView,
  normalizeCompose,
  pruneBlankComposeData,
} from './types.ts'
export {
  composeDocumentToRuntimeYaml,
  composeDocumentToYaml,
  ComposeParseError,
  yamlToComposeDocument,
} from './convert.ts'
export { mergeComposeDocuments, mergeComposeOverlay } from './merge.ts'
export {
  COMPOSE_CUSTOM_TAGS,
  COMPOSE_TAG_KEY,
  type ComposeTaggedValue,
  type ComposeTagName,
  composeTagOf,
  isComposeTaggedValue,
  makeComposeTag,
  resolveComposeTags,
  unwrapComposeTag,
} from './tags.ts'
export {
  collectSiteServiceNames,
  type ComposeLayer,
  type ComposeLayerRole,
  mergeComposeLayers,
  renameComposeVolumesInLayer,
  stripComposePlacementFromLayer,
  stripSiteServicesFromLayer,
} from './layers.ts'
export { stripComposeTurbopanelExtensions } from './extensions.ts'
export {
  type Application,
  type ApplicationPrincipal,
  type ApplicationProject,
  type ApplicationService,
  applicationService,
  buildApplicationModel,
  buildResolvedApplication,
  type ComposeServiceNode,
  containerServiceNames,
  hostNativeServiceNames,
  localComposeServiceNames,
  type PreparedNativeAppService,
  principalAliasByServiceName,
  type ResolvedApplication,
  type ResolvedContainerInput,
  type ResolvedPrincipal,
  type ResolvedResources,
  type ResolvedService,
  type ResolvedSlot,
  type ResolvedSlotInput,
  type ServerDeployment,
  serviceIdsOnServer,
} from './ir.ts'
export { renameComposeVolumes } from './rename-volumes.ts'
export { expandComposeServiceInstances } from './expand-instances.ts'
export {
  compileRuntimeCompose,
  compileRuntimeComposeDocument,
  type CompileRuntimeOptions,
  type CompileRuntimeResult,
} from './compile-runtime.ts'
export { SHA256_HEX_RE, sha256HexUtf8 } from './desired-hash.ts'
export {
  collectComposeExternalDockerNetworkNames,
  collectServiceComposeNetworkKeys,
  pruneUnreferencedComposeNetworks,
  readComposeExternalDockerNetworkName,
} from './docker-external-networks.ts'
export {
  applyValidatedComposeOption,
  assertComposeDocument,
  type ComposeValidateOptions,
  type ComposeValidationIssue,
  type ComposeValidationResult,
  stripComposePlacementOption,
  stripProjectComposePlacementOption,
  validateComposeDocument,
} from './validate.ts'
export {
  blockingComposeLintIssues,
  type ComposeLintCode,
  type ComposeLintIssue,
  type ComposeLintLevel,
  type ComposeLintOptions,
  lintComposeYaml,
} from './lint.ts'
export {
  classifyDeployKey,
  classifyDeployPlacementKey,
  classifyServiceKey,
  classifyTopLevelKey,
  type ComposeFieldPolicy,
  type ComposeFieldState,
  DEPLOY_FIELD_KEYS,
  DEPLOY_KEYS_STRIPPED_FROM_RUNTIME,
  SERVICE_FIELD_KEYS,
  TOP_LEVEL_FIELD_KEYS,
  unsupportedDeployReason,
} from './field-policy.ts'
export {
  COMPOSE_SPEC_SCHEMA_REVISION,
  validateAgainstUpstreamSchema,
} from './upstream-schema.ts'
export {
  type ComposeDeployValidationError,
  type ComposeMergedInvalidError,
  type ComposeUnsupportedFieldError,
  validateComposeForDeploy,
} from './validate-for-deploy.ts'
export {
  applyComposePlacement,
  isPlacementServerId,
  stripComposePlacement,
  TURBOPANEL_EXTENSION_KEY,
  type TurbopanelRuntimeRootExtension,
} from './placement.ts'
export {
  collectHostingExtensionValidationIssues,
  type ComposeHostingBindScope,
  type ComposeHostingBindSpec,
  type ComposeHostingExtensionEntry,
  type ComposeHostingTlsMode,
  type ComposeHostingTlsSpec,
  DEFAULT_HOSTING_BIND_SCOPE,
  DEFAULT_HOSTING_PATH_PREFIX,
  DEFAULT_HOSTING_TLS_MODE,
  HOSTING_BIND_SCOPES,
  HOSTING_ENTRY_KEYS,
  HOSTING_HOSTNAME_MAX_LENGTH,
  HOSTING_HOSTNAME_RE,
  HOSTING_HOSTNAME_REQUIRED_MESSAGE,
  HOSTING_KEY_REDIRECTS,
  HOSTING_NOT_A_PUBLISH_MESSAGE,
  HOSTING_PATH_PREFIX_MESSAGE,
  HOSTING_REF_MAX_LENGTH,
  HOSTING_TARGET_PORT_NOT_FOR_NODE_MESSAGE,
  HOSTING_TARGET_PORT_NOT_FOR_SITE_MESSAGE,
  HOSTING_TARGET_PORT_RANGE_MESSAGE,
  HOSTING_TLS_MODE_AUTOMATIC_UNSUPPORTED_MESSAGE,
  HOSTING_TLS_MODES,
  hostingBindScopeOf,
  hostingEntryKey,
  hostingIpRefUnresolvedMessage,
  hostingPathPrefixOf,
  hostingTargetPortAuthorable,
  hostingTlsModeOf,
  hostingTlsRefUnresolvedMessage,
  isHostingBindScope,
  isHostingTlsMode,
  MAX_HOSTING_ENTRIES_PER_SERVICE,
  parseHostingExtensionEntries,
  readHostingHostname,
  readHostingPathPrefix,
} from './hosting-extension.ts'
export {
  AUTHORED_ROOT_EXTENSION_KEYS,
  collectRootExtensionValidationIssues,
  DEFAULT_PRINCIPAL_ACCESS,
  isPrincipalAccess,
  isPrincipalAlias,
  parseRootExtension,
  PLACEMENT_NOT_STORED_MESSAGE,
  PRINCIPAL_ACCESS_VALUES,
  PRINCIPAL_ALIAS_RE,
  type PrincipalAccess,
  principalAccessOf,
  principalAliasesInComposeData,
  type PrincipalSpec,
  ROOT_KEY_REDIRECTS,
  type TurbopanelRootExtension,
  TURBOPANEL_ROOT_EXTENSION_KEY,
} from './root-extension.ts'
export {
  collectServiceTurbopanelValidationIssues,
  type ComposeContainerServiceExtension,
  type ComposeNodeServiceExtension,
  type ComposeServiceKind,
  type ComposeServiceSourceExtension,
  type ComposeServiceTurbopanelExtension,
  type ComposeSiteServiceExtension,
  type ComposeSourceBuildKind,
  DEFAULT_NODE_SERIES,
  isHostNativeServiceKind,
  isNodeComposeService,
  isSafeRoot,
  isSiteComposeService,
  type NativeRuntimeFramework,
  type NodeAppMode,
  type NodePackageManager,
  parseServiceSourceExtension,
  parseServiceTurbopanelExtension,
  readServiceSourceExtension,
  readServiceTurbopanelExtension,
  SERVICE_KIND_FIELD_TABLE,
  type ServiceKindFieldRules,
  SOURCE_BRANCH_MAX_LENGTH,
  SOURCE_COMMAND_MAX_LENGTH,
  type SourceIdResolver,
  type SiteEngine,
  SUPPORTED_NODE_SERIES,
  TURBOPANEL_SERVICE_EXTENSION_KEY,
} from './service-kind.ts'
export {
  assignNativeAppListenPorts,
  NATIVE_APP_DEFAULT_FRAMEWORK,
  NATIVE_APP_RESTART_CONDITIONS,
  type NativeAppRestartPolicy,
  type NativeAppRestartPolicyField,
  type NativeAppRestartPolicyRead,
  type NativeAppServiceSpec,
  readNativeAppRestartPolicy,
  readNativeAppServiceLabels,
  type SplitNativeAppResult,
  splitNativeAppServices,
} from './native-app.ts'
export {
  allocateSiteListenPort,
  assignSiteListenPorts,
  emptyContainerComposeYaml,
  isSafeSiteRoot,
  type SplitSiteResult,
  splitSiteServices,
  type SiteSpec,
} from './site.ts'
export {
  type ApplyVariablesError,
  type ApplyVariablesResult,
  applyVariablesToComposeDocument,
  type DeployVariableEntry,
  type DeployVariableMaterial,
  escapeLiteralComposeValue,
  isApplyVariablesError,
  trimVariableValue,
} from './apply-variables.ts'
export { type DeploySecretPlanEntry } from './secret-files.ts'
export {
  type ParsedVariableRef,
  parseExactVariableRef,
  type VariableRefScope,
} from './variable-refs.ts'
export {
  applyResourcesToComposeService,
  type ApplyServiceOptionsResult,
  applyServiceOptionsToComposeDocument,
  buildServiceOptionsMap,
  collectHealthCheckWarnings,
  type HealthCheckWarning,
  type ServiceDeployHook,
  serviceHasComposeHealthCheck,
  type ServiceOptionsByComposeName,
} from './apply-service-options.ts'
