networks:
  tp-net:
    name: tp-net

services:
  turbopanel:
    image: ghcr.io/turbopanel/turbopanel:1.0-development
    container_name: turbopanel
    hostname: turbopanel
    restart: always
    volumes:
      - .:/opt/turbopanel
    networks:
      - tp-net
    ports:
      - 2052:2052
      - 2053:2053
      - 2082:2082
      - 2083:2083
      - 2086:2086
      - 2087:2087
      - 2095:2095
      - 2096:2096
      - 7080:7080

  turbopanel-db:
    image: mariadb:10.11-jammy
    container_name: turbopanel-db
    hostname: turbopanel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: turbopanel
      MYSQL_USER: turbopanel
      MYSQL_PASSWORD: turbopanel
    networks:
      - tp-net
    ports:
      - 3306:3306
