networks:
  tp-net:
    name: tp-net
  tp-cache-net:
    name: tp-cache-net

services:
  app:
    image: ghcr.io/turbopanel/turbopanel:1.0-development
    container_name: turbopanel
    hostname: turbopanel
    restart: always
    volumes:
      - .:/opt/turbopanel
    networks:
      - tp-net
      - tp-cache-net
    ports:
      - 2052:2052
      - 2053:2053
      - 2082:2082
      - 2083:2083
      - 2086:2086
      - 2087:2087
      - 2095:2095
      - 2096:2096
      - 7080:7080

  db:
    image: mariadb:10.11-jammy
    container_name: turbopanel-db
    hostname: turbopanel-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: c5NcrPJhQuUaD4cEmj9o
      MYSQL_DATABASE: turbopanel
      MYSQL_USER: turbopanel
      MYSQL_PASSWORD: turbopanel
    networks:
      - tp-net
    ports:
      - 3306:3306

  cache:
    image: redis:6.2.6
    container_name: turbopanel-cache
    hostname: turbopanel-cache
    restart: always
    networks:
      - tp-net
      - tp-cache-net
    ports:
      - 6379:6379
