interface CloudflareBindings {
  /** Durable Object namespace for per-server daemon cells. Regenerated by `pnpm cf-typegen` after wrangler.jsonc changes. */
  DAEMON_CELL: DurableObjectNamespace
  HYPERDRIVE?: Hyperdrive
  TURBOPANEL_SECRET?: string
  TURBOPANEL_SECRETS?: string
  TURBOPANEL_DATABASE_URL?: string
  TURBOPANEL_UI_CORS_ORIGINS?: string
  TURBOPANEL_IS_SIGNUP_ENABLED?: string | number
  TURBOPANEL_IS_SIGNUP_EMAIL_VERIFICATION_ENABLED?: string
  TURBOPANEL_MAILGUN_API_KEY?: string
  TURBOPANEL_MAILGUN_DOMAIN?: string
  TURBOPANEL_SYSTEM_EMAIL_FROM?: string
  TURBOPANEL_BASE_URL?: string
  TURBOPANEL_PBKDF2_ITERATIONS?: string
  /** When `1` or `true`, expose dev-only admin OpenAPI/Scalar routes (`wrangler dev` only). */
  TURBOPANEL_DEV_SURFACE?: string
}
