interface CloudflareBindings {
  HYPERDRIVE?: Hyperdrive
  TURBOPANEL_SECRET?: string
  TURBOPANEL_SECRETS?: string
  TURBOPANEL_CORS_ORIGINS?: string
  TURBOPANEL_IS_SIGNUP_ENABLED?: string
  TURBOPANEL_MAILGUN_API_KEY?: string
  TURBOPANEL_MAILGUN_DOMAIN?: string
  TURBOPANEL_SYSTEM_EMAIL_FROM?: string
  TURBOPANEL_BASE_URL?: string
}
