/** Cloudflare Workers Rate Limiting API — confirmed via `pnpm cf-typegen`. */
interface RateLimitOptions {
  key: string
}
interface RateLimitOutcome {
  success: boolean
}
interface RateLimit {
  /**
   * Rate limit a request based on the provided options.
   * @see https://developers.cloudflare.com/workers/runtime-apis/bindings/rate-limit/
   */
  limit(options: RateLimitOptions): Promise<RateLimitOutcome>
}

/** Mirrors Workers `AnalyticsEngineDataset` from `@cloudflare/workers-types`. */
interface AnalyticsEngineDataset {
  writeDataPoint(event?: AnalyticsEngineDataPoint): void
}

interface AnalyticsEngineDataPoint {
  indexes?: ((ArrayBuffer | string) | null)[]
  doubles?: number[]
  blobs?: ((ArrayBuffer | string) | null)[]
}

/**
 * Structural mirror of the Workers Pipelines binding (`env.<BINDING>.send`).
 *
 * Hand-declared rather than generated: this file is maintained by hand (see the
 * header) and the installed `@cloudflare/workers-types` does not ship a
 * `Pipeline` interface. `src/lib/container-logs/cloudflare/pipeline-store.ts`
 * consumes the narrower `PipelineLike` so the Deno type-check needs no Workers
 * types at all.
 */
interface Pipeline {
  send(records: unknown[]): Promise<void>
}

interface CloudflareBindings {
  /** Durable Object namespace for per-server daemon cells. Regenerated by `pnpm cf-typegen` after wrangler.jsonc changes. */
  DAEMON_CELL: DurableObjectNamespace
  /** Non-cached Hyperdrive (operator disables caching on this config). Regenerated by `pnpm cf-typegen` after wrangler.jsonc changes. */
  HYPERDRIVE?: Hyperdrive
  /** Cached Hyperdrive for read-heavy paths. Regenerated by `pnpm cf-typegen` after wrangler.jsonc changes. */
  HYPERDRIVE_CACHED?: Hyperdrive
  /** WS-upgrade / reconnect rate limit. Regenerated by `pnpm cf-typegen` after wrangler.jsonc changes. */
  DAEMON_CONNECT_RATE_LIMITER?: RateLimit
  /** Daemon REST rate limit (enroll/challenge/session/lease/decrypt). Regenerated by `pnpm cf-typegen` after wrangler.jsonc changes. */
  DAEMON_REST_RATE_LIMITER?: RateLimit
  /**
   * Host-metrics ingest rate limit (~1/min/server). Missing binding fails closed
   * on production-like Workers (see `resolveWorkersDaemonRateLimiters`).
   * Regenerated by `pnpm cf-typegen` after wrangler.jsonc changes.
   */
  DAEMON_METRICS_RATE_LIMITER?: RateLimit
  /**
   * Container-log ingest rate limit (`POST /api/daemon/v1/logs/containers`).
   * Dedicated so batched container output cannot spend the shared daemon REST
   * budget. Missing binding fails closed on production-like Workers (see
   * `resolveWorkersDaemonRateLimiters`).
   * Regenerated by `pnpm cf-typegen` after wrangler.jsonc changes.
   */
  CONTAINER_LOGS_RATE_LIMITER?: RateLimit
  /**
   * Client auth throttle (sign-in / sign-up / OTP / install), globally shared
   * across isolates. Production Workers must bind this; a missing binding fails
   * auth endpoints closed (see `resolveWorkersClientAuthRateLimiter`).
   * Regenerated by `pnpm cf-typegen` after wrangler.jsonc changes.
   */
  CLIENT_AUTH_RATE_LIMITER?: RateLimit
  /**
   * Inbound GitHub webhook throttle (`/api/git/v1/github/webhook`). Keyed per
   * peer address because the caller has no identity until its HMAC is verified.
   * Missing binding fails closed on production-like Workers (see
   * `resolveWorkersGithubWebhookRateLimiter`).
   * Regenerated by `pnpm cf-typegen` after wrangler.jsonc changes.
   */
  GITHUB_WEBHOOK_RATE_LIMITER?: RateLimit
  /**
   * Inbound GitLab webhook throttle (`/api/git/v1/gitlab/webhook`). Keyed per
   * peer address, like GitHub's, and a separate bucket so one provider's burst
   * cannot spend the other's budget. Missing binding fails closed on
   * production-like Workers (see `resolveWorkersGitlabWebhookRateLimiter`).
   * Regenerated by `pnpm cf-typegen` after wrangler.jsonc changes.
   */
  GITLAB_WEBHOOK_RATE_LIMITER?: RateLimit
  TURBOPANEL_SECRET?: string
  TURBOPANEL_SECRETS?: string
  TURBOPANEL_DATABASE_URL?: string
  TURBOPANEL_UI_CORS_ORIGINS?: string
  TURBOPANEL_IS_SIGNUP_ENABLED?: string | number
  TURBOPANEL_SYSTEM_EMAIL__PROVIDER?: string
  TURBOPANEL_SYSTEM_EMAIL__MAILGUN_API_KEY?: string
  TURBOPANEL_SYSTEM_EMAIL__MAILGUN_DOMAIN?: string
  TURBOPANEL_SYSTEM_EMAIL__FROM?: string
  TURBOPANEL_BASE_URL?: string
  /** When `1` or `true`, expose dev-only admin OpenAPI/Scalar routes (`wrangler dev` only). */
  TURBOPANEL_DEV_SURFACE?: string
  /** When `1` or `true`, enable verbose daemon-cell debug logging. */
  TURBOPANEL_DAEMON_DEBUG?: string
  /** Raise-only Argon2id memory cost (KiB); ignored when below the OWASP floor (19456). */
  TURBOPANEL_ARGON2ID_MEMORY_KIB?: string
  /** Raise-only Argon2id time cost (t); ignored when below the OWASP floor (2). */
  TURBOPANEL_ARGON2ID_TIME_COST?: string
  /** Cloudflare account id for Analytics Engine SQL API queries. */
  CLOUDFLARE_ACCOUNT_ID?: string
  /** Account Analytics Read token for AE SQL API (secret). */
  TURBOPANEL_ANALYTICS_ENGINE_API_TOKEN?: string
  /**
   * Optional override for AE SQL max query range in seconds.
   * Default is documented Analytics Engine retention (90 days).
   */
  TURBOPANEL_SERVER_METRICS_AE_MAX_RANGE_SECONDS?: string
  /** Workers Analytics Engine dataset binding for host metrics writes. */
  SERVER_METRICS?: AnalyticsEngineDataset
  /**
   * R2 bucket holding command transcripts (execution logs). Bucket is not
   * auto-created — see wrangler.jsonc. Regenerated by `pnpm cf-typegen` after
   * wrangler.jsonc changes.
   */
  EXECUTION_LOGS?: R2Bucket
  /**
   * Transcript retention window in days (positive integer). Anything else
   * falls back to the 30-day default — parity with the Deno
   * `TURBOPANEL_EXECUTION_LOG_RETENTION_DAYS` env var.
   */
  TURBOPANEL_EXECUTION_LOG_RETENTION_DAYS?: string
  /**
   * Pipelines binding for container-log ingest. The Stream sinks into an
   * Apache Iceberg table in R2 Data Catalog; reads go back out through R2 SQL.
   * Not auto-created — see wrangler.jsonc.
   */
  CONTAINER_LOGS?: Pipeline
  /** Container-log opt-in gate (default-off; 1/true/yes/on enables). */
  TURBOPANEL_CONTAINER_LOGS_ENABLED?: string
  /** R2 SQL + R2 Data Catalog + R2 storage read token (secret). */
  TURBOPANEL_CONTAINER_LOGS_R2_SQL_API_TOKEN?: string
  /** R2 bucket backing the Data Catalog warehouse the Iceberg table lives in. */
  TURBOPANEL_CONTAINER_LOGS_R2_SQL_BUCKET?: string
  /** Catalog identifier of the container-log table, as `namespace.table`. */
  TURBOPANEL_CONTAINER_LOGS_ICEBERG_TABLE?: string
  /**
   * Optional override for the R2 SQL max query range in seconds.
   * Default is the documented container-log retention (30 days).
   */
  TURBOPANEL_CONTAINER_LOGS_R2_SQL_MAX_RANGE_SECONDS?: string
  /** Max inbound WS messages per connection per window (DO in-memory cap; default 120). */
  TURBOPANEL_DAEMON_WS_INBOUND_LIMIT?: string
  /** Inbound WS flood window in ms (DO in-memory cap; default 60000). */
  TURBOPANEL_DAEMON_WS_INBOUND_WINDOW_MS?: string
  /** Cloudflare Queue binding for command dispatch. Regenerated by `pnpm cf-typegen` after wrangler.jsonc changes. */
  TURBOPANEL_COMMAND_QUEUE?: Queue
}

/**
 * wrangler / `@cloudflare/vitest-pool-workers` type `env` as `Cloudflare.Env`
 * (and Deno LSP as global `Env`). Keep those aliases in lockstep with
 * {@link CloudflareBindings} after `pnpm cf-typegen` regenerates this file.
 */
declare namespace Cloudflare {
  interface Env extends CloudflareBindings {}
}

interface Env extends CloudflareBindings {}
