-- Custom SQL migration: Postgres COMMENT ON for the reorg path of tier.label.
-- Generated by `node scripts/schema-comments.mjs` from src/db/schema-descriptions.ts;
-- see src/db/AGENTS.md → "Schema descriptions". Comments only, no DDL.
COMMENT ON COLUMN "tier"."label" IS 'Ladder label `S1` to `S7` or `SX`, the unique key into the in-code ladder (`src/features/tiers/ladder.ts`) that holds everything the tier entitles.';--> statement-breakpoint
